name: Python Playwright CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest playwright

      - name: Install Playwright browsers
        run: playwright install

      - name: Run API tests only
        run: |
          pytest -m "api" --alluredir=allure-results/api
      - name: Install Allure CLI
        run: |
           npm install -g allure-commandline --save-dev

      - name: Generate Allure Report for API
        run: |
          allure generate allure-results/api --clean -o allure-report/api

      - name: Upload API Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-api
          path: allure-report/api

  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest playwright

      - name: Install Playwright browsers
        run: playwright install

      - name: Install Allure CLI
        run: |
           npm install -g allure-commandline --save-dev
           
      - name: Run UI tests (skip broken, continue on failure)
        run: |
          pytest -m "ui and not broken" --alluredir=allure-results/ui || true

      - name: Generate Allure Report for UI
        run: |
          allure generate allure-results/ui --clean -o allure-report/ui

      - name: Upload UI Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-ui
          path: allure-report/ui
